version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]  # Проверяет статус RabbitMQ
      interval: 10s                           # Проверка каждые 10 секунд
      timeout: 5s                             # Таймаут проверки
      retries: 5                              # Количество попыток
    networks:
      - app-network
  mongodb:
    image: mongo:6.0 
    container_name: mongodb
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: password  # Пароль для администратора
    volumes:
      - mongodb_data:/data/db 
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"] 
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "50054:50054"
    environment:
      RABBITMQ_URL: "amqp://user:password@rabbitmq:5672/"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge