// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: pkg/proto/basket.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint64                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         uint64                 `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_pkg_proto_basket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_basket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_pkg_proto_basket_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Basket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        uint64                 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	FullPrice     uint64                 `protobuf:"varint,2,opt,name=FullPrice,proto3" json:"FullPrice,omitempty"`
	Products      []*Product             `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Basket) Reset() {
	*x = Basket{}
	mi := &file_pkg_proto_basket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Basket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basket) ProtoMessage() {}

func (x *Basket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_basket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basket.ProtoReflect.Descriptor instead.
func (*Basket) Descriptor() ([]byte, []int) {
	return file_pkg_proto_basket_proto_rawDescGZIP(), []int{1}
}

func (x *Basket) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Basket) GetFullPrice() uint64 {
	if x != nil {
		return x.FullPrice
	}
	return 0
}

func (x *Basket) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type NewBasketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        uint64                 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewBasketReq) Reset() {
	*x = NewBasketReq{}
	mi := &file_pkg_proto_basket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewBasketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBasketReq) ProtoMessage() {}

func (x *NewBasketReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_basket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBasketReq.ProtoReflect.Descriptor instead.
func (*NewBasketReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_basket_proto_rawDescGZIP(), []int{2}
}

func (x *NewBasketReq) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_proto_basket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_basket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_proto_basket_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasketID      uint64                 `protobuf:"varint,1,opt,name=BasketID,proto3" json:"BasketID,omitempty"`
	Product       *Product               `protobuf:"bytes,2,opt,name=Product,proto3" json:"Product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductReq) Reset() {
	*x = AddProductReq{}
	mi := &file_pkg_proto_basket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductReq) ProtoMessage() {}

func (x *AddProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_basket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductReq.ProtoReflect.Descriptor instead.
func (*AddProductReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_basket_proto_rawDescGZIP(), []int{4}
}

func (x *AddProductReq) GetBasketID() uint64 {
	if x != nil {
		return x.BasketID
	}
	return 0
}

func (x *AddProductReq) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetBasketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasketID      uint64                 `protobuf:"varint,1,opt,name=BasketID,proto3" json:"BasketID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasketReq) Reset() {
	*x = GetBasketReq{}
	mi := &file_pkg_proto_basket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketReq) ProtoMessage() {}

func (x *GetBasketReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_basket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketReq.ProtoReflect.Descriptor instead.
func (*GetBasketReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_basket_proto_rawDescGZIP(), []int{5}
}

func (x *GetBasketReq) GetBasketID() uint64 {
	if x != nil {
		return x.BasketID
	}
	return 0
}

type GetBasketResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basket        *Basket                `protobuf:"bytes,1,opt,name=Basket,proto3" json:"Basket,omitempty"`
	Response      *Response              `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasketResp) Reset() {
	*x = GetBasketResp{}
	mi := &file_pkg_proto_basket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasketResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketResp) ProtoMessage() {}

func (x *GetBasketResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_basket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketResp.ProtoReflect.Descriptor instead.
func (*GetBasketResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_basket_proto_rawDescGZIP(), []int{6}
}

func (x *GetBasketResp) GetBasket() *Basket {
	if x != nil {
		return x.Basket
	}
	return nil
}

func (x *GetBasketResp) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type DeleteProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasketID      uint64                 `protobuf:"varint,1,opt,name=BasketID,proto3" json:"BasketID,omitempty"`
	ProductID     uint64                 `protobuf:"varint,2,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductReq) Reset() {
	*x = DeleteProductReq{}
	mi := &file_pkg_proto_basket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductReq) ProtoMessage() {}

func (x *DeleteProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_basket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductReq.ProtoReflect.Descriptor instead.
func (*DeleteProductReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_basket_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProductReq) GetBasketID() uint64 {
	if x != nil {
		return x.BasketID
	}
	return 0
}

func (x *DeleteProductReq) GetProductID() uint64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

var File_pkg_proto_basket_proto protoreflect.FileDescriptor

var file_pkg_proto_basket_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x64, 0x0a,
	0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1c, 0x0a, 0x09, 0x46, 0x75, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x46, 0x75, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x22, 0x26, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x38, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4f, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x49, 0x44, 0x12, 0x22, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x22, 0x2a, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x49, 0x44, 0x22, 0x57, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x06, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4c, 0x0a, 0x10, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x32, 0xae, 0x01, 0x0a, 0x0d, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x4e,
	0x65, 0x77, 0x12, 0x0d, 0x2e, 0x4e, 0x65, 0x77, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0a,
	0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0e, 0x2e, 0x41, 0x64, 0x64,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0d, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x0d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x11, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_basket_proto_rawDescOnce sync.Once
	file_pkg_proto_basket_proto_rawDescData = file_pkg_proto_basket_proto_rawDesc
)

func file_pkg_proto_basket_proto_rawDescGZIP() []byte {
	file_pkg_proto_basket_proto_rawDescOnce.Do(func() {
		file_pkg_proto_basket_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_basket_proto_rawDescData)
	})
	return file_pkg_proto_basket_proto_rawDescData
}

var file_pkg_proto_basket_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_proto_basket_proto_goTypes = []any{
	(*Product)(nil),          // 0: product
	(*Basket)(nil),           // 1: basket
	(*NewBasketReq)(nil),     // 2: NewBasketReq
	(*Response)(nil),         // 3: Response
	(*AddProductReq)(nil),    // 4: AddProductReq
	(*GetBasketReq)(nil),     // 5: GetBasketReq
	(*GetBasketResp)(nil),    // 6: GetBasketResp
	(*DeleteProductReq)(nil), // 7: DeleteProductReq
}
var file_pkg_proto_basket_proto_depIdxs = []int32{
	0, // 0: basket.products:type_name -> product
	0, // 1: AddProductReq.Product:type_name -> product
	1, // 2: GetBasketResp.Basket:type_name -> basket
	3, // 3: GetBasketResp.response:type_name -> Response
	2, // 4: BasketService.New:input_type -> NewBasketReq
	4, // 5: BasketService.AddProduct:input_type -> AddProductReq
	5, // 6: BasketService.Get:input_type -> GetBasketReq
	7, // 7: BasketService.DeleteProduct:input_type -> DeleteProductReq
	3, // 8: BasketService.New:output_type -> Response
	3, // 9: BasketService.AddProduct:output_type -> Response
	6, // 10: BasketService.Get:output_type -> GetBasketResp
	3, // 11: BasketService.DeleteProduct:output_type -> Response
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_basket_proto_init() }
func file_pkg_proto_basket_proto_init() {
	if File_pkg_proto_basket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_basket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_basket_proto_goTypes,
		DependencyIndexes: file_pkg_proto_basket_proto_depIdxs,
		MessageInfos:      file_pkg_proto_basket_proto_msgTypes,
	}.Build()
	File_pkg_proto_basket_proto = out.File
	file_pkg_proto_basket_proto_rawDesc = nil
	file_pkg_proto_basket_proto_goTypes = nil
	file_pkg_proto_basket_proto_depIdxs = nil
}
